// ============================================================
// WITA — POTION DATA
// Ingredient/recipe metadata sourced from the dependency module:
//   potion-crafting-and-gathering  (by theripper93 / action-jay)
//
// Level/EXP/gate tables live in potion-config.js.
// ============================================================

export const WITA_POTION_FLAG_NS = "wita";
export const WITA_DEP_MODULE_ID  = "potion-crafting-and-gathering";

export const WITA_DEP_PACKS = {
    ingredients: `${WITA_DEP_MODULE_ID}.potion-crafting-and-gathering-ingredients`,
    alchemy:     `${WITA_DEP_MODULE_ID}.potion-crafting-and-gathering-alchemy`,
    herbalism:   `${WITA_DEP_MODULE_ID}.potion-crafting-and-gathering-herbalism`,
    poisons:     `${WITA_DEP_MODULE_ID}.potion-crafting-and-gathering-poisons`,
};

export const WITA_POTION_ENVIRONMENTS = [
    "Arctic","Blightshore Caves","Coasts","Deserts","Feywild",
    "Forests","Grasslands","Hills","Savanah","Sites of frequent death",
    "Swamps","Underdark","Urban areas","Volcanos","Wyvern poison burned soil",
];

export const WITA_INGREDIENT_META = {
    "Acid Dew":                 { gatherDC:15, harvestDC:20, quantity:"1d6",   gatherRarity:"uncommon", locations:["Swamps","Forests"] },
    "Angel's Trumpet":          { gatherDC:20, harvestDC:15, quantity:"1d8",   gatherRarity:"rare",     locations:["Forests","Hills"] },
    "Ashblossom":               { gatherDC:20, harvestDC:15, quantity:"1d6",   gatherRarity:"rare",     locations:["Deserts","Volcanos"] },
    "Bane Berry":               { gatherDC:15, harvestDC:15, quantity:"2d4",   gatherRarity:"uncommon", locations:["Urban areas"] },
    "Black Cap Mushroom":       { gatherDC:20, harvestDC:20, quantity:"1d4",   gatherRarity:"rare",     locations:["Forests","Swamps"] },
    "Black Sap":                { gatherDC:20, harvestDC:15, quantity:"1d6",   gatherRarity:"rare",     locations:["Sites of frequent death"] },
    "Black Thistle":            { gatherDC:20, harvestDC:20, quantity:"1d4+1", gatherRarity:"rare",     locations:["Wyvern poison burned soil"] },
    "Blight Spores":            { gatherDC:20, harvestDC:15, quantity:"1d6",   gatherRarity:"rare",     locations:["Blightshore Caves"] },
    "Bloodroot":                { gatherDC:15, harvestDC:10, quantity:"1d8",   gatherRarity:"uncommon", locations:["Grasslands","Savanah"] },
    "Cat's Tongue":             { gatherDC:10, harvestDC:10, quantity:"2d4",   gatherRarity:"common",   locations:["Grasslands","Forests"] },
    "Death Cap":                { gatherDC:20, harvestDC:20, quantity:"1d4",   gatherRarity:"rare",     locations:["Forests","Swamps"] },
    "Dreamlily":                { gatherDC:10, harvestDC:10, quantity:"2d6",   gatherRarity:"common",   locations:["Grasslands","Coasts"] },
    "Everfrost Berries":        { gatherDC:10, harvestDC:5,  quantity:"3d6",   gatherRarity:"common",   locations:["Grasslands","Forests"] },
    "Fairy Stool":              { gatherDC:20, harvestDC:15, quantity:"1d4",   gatherRarity:"rare",     locations:["Feywild","Forests"] },
    "Fire Peas":                { gatherDC:15, harvestDC:15, quantity:"1d6",   gatherRarity:"uncommon", locations:["Deserts","Savanah"] },
    "Flame Lily":               { gatherDC:15, harvestDC:15, quantity:"1d8",   gatherRarity:"uncommon", locations:["Deserts","Savanah"] },
    "Frost Lichen":             { gatherDC:15, harvestDC:15, quantity:"1d6",   gatherRarity:"uncommon", locations:["Arctic"] },
    "Gillyweed":                { gatherDC:10, harvestDC:10, quantity:"2d4",   gatherRarity:"common",   locations:["Coasts","Swamps"] },
    "Hagfinger":                { gatherDC:20, harvestDC:15, quantity:"1d4",   gatherRarity:"rare",     locations:["Forests","Swamps"] },
    "Idle Claws":               { gatherDC:20, harvestDC:15, quantity:"1d4",   gatherRarity:"rare",     locations:["Swamps","Forests"] },
    "Lightning Moss":           { gatherDC:15, harvestDC:15, quantity:"1d6",   gatherRarity:"uncommon", locations:["Hills","Forests"] },
    "Mandrake Root":            { gatherDC:20, harvestDC:15, quantity:"1d4",   gatherRarity:"rare",     locations:["Forests","Hills"] },
    "Mindflayer Stinkhorn":     { gatherDC:20, harvestDC:15, quantity:"1d4",   gatherRarity:"rare",     locations:["Forests","Underdark"] },
    "Moonstalker":              { gatherDC:20, harvestDC:15, quantity:"1d4",   gatherRarity:"rare",     locations:["Forests","Swamps"] },
    "Morning Dew":              { gatherDC:15, harvestDC:10, quantity:"1d6",   gatherRarity:"uncommon", locations:["Grasslands","Forests"] },
    "Muroosa Bush":             { gatherDC:10, harvestDC:10, quantity:"2d4",   gatherRarity:"common",   locations:["Deserts","Grasslands"] },
    "Nightshade":               { gatherDC:10, harvestDC:10, quantity:"2d4",   gatherRarity:"common",   locations:["Forests","Grasslands"] },
    "Olisuba Leaf":             { gatherDC:15, harvestDC:10, quantity:"2d4",   gatherRarity:"uncommon", locations:["Forests","Swamps"] },
    "Pixie's Parasol":          { gatherDC:15, harvestDC:10, quantity:"1d6",   gatherRarity:"uncommon", locations:["Feywild","Forests"] },
    "Rainbow Mushroom":         { gatherDC:15, harvestDC:10, quantity:"1d4",   gatherRarity:"uncommon", locations:["Feywild","Forests"] },
    "Red Amanita Mushroom":     { gatherDC:10, harvestDC:10, quantity:"2d4",   gatherRarity:"common",   locations:["Forests","Grasslands"] },
    "Silverthorn":              { gatherDC:20, harvestDC:15, quantity:"1d4",   gatherRarity:"rare",     locations:["Hills","Forests"] },
    "Singing Nettle":           { gatherDC:15, harvestDC:15, quantity:"1d6",   gatherRarity:"uncommon", locations:["Grasslands","Forests"] },
    "Sourgrass":                { gatherDC:10, harvestDC:10, quantity:"2d6",   gatherRarity:"common",   locations:["Grasslands","Forests"] },
    "Theki Root":               { gatherDC:15, harvestDC:10, quantity:"1d6",   gatherRarity:"uncommon", locations:["Forests","Swamps"] },
    "The Bearded Green":        { gatherDC:15, harvestDC:10, quantity:"1d6",   gatherRarity:"uncommon", locations:["Forests","Swamps"] },
    "White Ghost Orchid Seed":  { gatherDC:20, harvestDC:15, quantity:"1d4",   gatherRarity:"rare",     locations:["Swamps","Feywild"] },
    "Willowshade Fruit":        { gatherDC:15, harvestDC:10, quantity:"1d6",   gatherRarity:"uncommon", locations:["Forests","Swamps"] },
    "Wolfsbane":                { gatherDC:20, harvestDC:15, quantity:"1d4",   gatherRarity:"rare",     locations:["Hills","Forests"] },
};

export const WITA_RECIPE_META = {
    // Alchemist – Common
    "Alchemist's Fire":              { kit:"alchemist", rarity:"common"   },
    "Bottled Breath":                { kit:"alchemist", rarity:"common"   },
    "Blasting Powder":               { kit:"alchemist", rarity:"common"   },
    "Fake Blood":                    { kit:"alchemist", rarity:"common"   },
    "Grenade, Smoke":                { kit:"alchemist", rarity:"common"   },
    "Ink, Spell Writing (Common)":   { kit:"alchemist", rarity:"common"   },
    "Potion of Climbing":            { kit:"alchemist", rarity:"common"   },
    "Potion of Swimming":            { kit:"alchemist", rarity:"common"   },
    "Soothsalts":                    { kit:"alchemist", rarity:"common"   },
    // Alchemist – Uncommon
    "Ink, Spell Writing (Uncommon)": { kit:"alchemist", rarity:"uncommon" },
    "Invisible Ink":                 { kit:"alchemist", rarity:"uncommon" },
    "Lesser Potion of Mana":         { kit:"alchemist", rarity:"uncommon" },
    "Midnight Oil":                  { kit:"alchemist", rarity:"uncommon" },
    "Oil of Slipperiness":           { kit:"alchemist", rarity:"uncommon" },
    "Pixie Dust":                    { kit:"alchemist", rarity:"uncommon" },
    "Potion of Animal Friendship":   { kit:"alchemist", rarity:"uncommon" },
    "Potion of Fire Breath":         { kit:"alchemist", rarity:"uncommon" },
    "Potion of Growth":              { kit:"alchemist", rarity:"uncommon" },
    "Potion of Resistance":          { kit:"alchemist", rarity:"uncommon" },
    "Potion of Water Breathing":     { kit:"alchemist", rarity:"uncommon" },
    // Alchemist – Rare
    "Ink, Spell Writing (Rare)":     { kit:"alchemist", rarity:"rare"     },
    "Oil of Dragon's Bane":          { kit:"alchemist", rarity:"rare"     },
    "Potion of Aqueous Form":        { kit:"alchemist", rarity:"rare"     },
    "Potion of Gaseous Form":        { kit:"alchemist", rarity:"rare"     },
    "Potion of Giant Strength":      { kit:"alchemist", rarity:"rare"     },
    "Potion of Mana":                { kit:"alchemist", rarity:"rare"     },
    "Potion of True Dreaming":       { kit:"alchemist", rarity:"rare"     },
    "Oil of Etherealness":           { kit:"alchemist", rarity:"rare"     },
    "Potion of Clairvoyance":        { kit:"alchemist", rarity:"rare"     },
    "Potion of Diminution":          { kit:"alchemist", rarity:"rare"     },
    "Potion of Heroism":             { kit:"alchemist", rarity:"rare"     },
    "Potion of Invulnerability":     { kit:"alchemist", rarity:"rare"     },
    "Potion of Mind Reading":        { kit:"alchemist", rarity:"rare"     },
    "Thor's Might":                  { kit:"alchemist", rarity:"rare"     },
    // Alchemist – Very Rare
    "Ink, Spell Writing (Very Rare)":{ kit:"alchemist", rarity:"veryRare" },
    "Oil of Sharpness":              { kit:"alchemist", rarity:"veryRare" },
    "Potion of Flying":              { kit:"alchemist", rarity:"veryRare" },
    "Potion of Invisibility":        { kit:"alchemist", rarity:"veryRare" },
    "Potion of Longevity":           { kit:"alchemist", rarity:"veryRare" },
    "Potion of Possibility":         { kit:"alchemist", rarity:"veryRare" },
    "Potion of Speed":               { kit:"alchemist", rarity:"veryRare" },
    "Potion of Truesight":           { kit:"alchemist", rarity:"veryRare" },
    "Superior Potion of Mana":       { kit:"alchemist", rarity:"veryRare" },
    // Herbalism – Common
    "Antitoxin":                     { kit:"herbalism", rarity:"common"   },
    "Potion of Healing":             { kit:"herbalism", rarity:"common"   },
    "Muroosa Balm":                  { kit:"herbalism", rarity:"common"   },
    "Pepper Peppers":                { kit:"herbalism", rarity:"common"   },
    "Potion of Plantspeak":          { kit:"herbalism", rarity:"common"   },
    "Soothing Salve":                { kit:"herbalism", rarity:"common"   },
    "Quenching Pilther":             { kit:"herbalism", rarity:"common"   },
    "Willowshade Oil":               { kit:"herbalism", rarity:"common"   },
    // Herbalism – Uncommon
    "Blight Ichor":                  { kit:"herbalism", rarity:"uncommon" },
    "Brew of Babel":                 { kit:"herbalism", rarity:"uncommon" },
    "Fire Balm":                     { kit:"herbalism", rarity:"uncommon" },
    "Forgetfulness Antidote":        { kit:"herbalism", rarity:"uncommon" },
    "Greater Antitoxin":             { kit:"herbalism", rarity:"uncommon" },
    "Keoghtom's Ointment":           { kit:"herbalism", rarity:"uncommon" },
    "Life's Liquor":                 { kit:"herbalism", rarity:"uncommon" },
    "Murgaxor's Elixir of Life":     { kit:"herbalism", rarity:"uncommon" },
    "Pomander of Warding":           { kit:"herbalism", rarity:"uncommon" },
    "Potion of Advantage":           { kit:"herbalism", rarity:"uncommon" },
    "Potion of Greater Healing":     { kit:"herbalism", rarity:"uncommon" },
    "Potion of Maximum Power":       { kit:"herbalism", rarity:"uncommon" },
    "Potion of Shapeshifting":       { kit:"herbalism", rarity:"uncommon" },
    "Tea of Refreshment":            { kit:"herbalism", rarity:"uncommon" },
    "Thessaltoxin Antidote":         { kit:"herbalism", rarity:"uncommon" },
    // Herbalism – Rare
    "Bottled Rest":                  { kit:"herbalism", rarity:"rare"     },
    "Elixir of Health":              { kit:"herbalism", rarity:"rare"     },
    "Liquid Luck":                   { kit:"herbalism", rarity:"rare"     },
    "Meditative Rest":               { kit:"herbalism", rarity:"rare"     },
    "Polymorph Potion":              { kit:"herbalism", rarity:"rare"     },
    "Potion of Restoration":         { kit:"herbalism", rarity:"rare"     },
    "Potion of Revival":             { kit:"herbalism", rarity:"rare"     },
    "Potion of Superior Healing":    { kit:"herbalism", rarity:"rare"     },
    "Tincture of Werewolf's Bane":   { kit:"herbalism", rarity:"rare"     },
    // Herbalism – Very Rare
    "Reincarnation Dust":            { kit:"herbalism", rarity:"veryRare" },
    "Potion of Continuous Healing":  { kit:"herbalism", rarity:"veryRare" },
    "Potion of Enhanced Reactions":  { kit:"herbalism", rarity:"veryRare" },
    "Potion of Legendary Resistance":{ kit:"herbalism", rarity:"veryRare" },
    "Potion of Protection":          { kit:"herbalism", rarity:"veryRare" },
    "Potion of Supreme Healing":     { kit:"herbalism", rarity:"veryRare" },
    "Potion of Vitality":            { kit:"herbalism", rarity:"veryRare" },
    "Vampiric Essence":              { kit:"herbalism", rarity:"veryRare" },
    // Poisoner – Common
    "Basic Poison":                  { kit:"poisoner",  rarity:"common"   },
    "Biza's Breath":                 { kit:"poisoner",  rarity:"common"   },
    "Dazzling Bomb":                 { kit:"poisoner",  rarity:"common"   },
    "Liquid Paranoia":               { kit:"poisoner",  rarity:"common"   },
    "Nausea Pellet":                 { kit:"poisoner",  rarity:"common"   },
    "Perfume of Bewitching":         { kit:"poisoner",  rarity:"common"   },
    // Poisoner – Uncommon
    "Angel's Powder":                { kit:"poisoner",  rarity:"uncommon" },
    "Assassin's Blood":              { kit:"poisoner",  rarity:"uncommon" },
    "Malice":                        { kit:"poisoner",  rarity:"uncommon" },
    "Pale Tincture":                 { kit:"poisoner",  rarity:"uncommon" },
    "Philter of Love":               { kit:"poisoner",  rarity:"uncommon" },
    "Truth Serum":                   { kit:"poisoner",  rarity:"uncommon" },
    // Poisoner – Rare
    "Burnt Othur Fumes":             { kit:"poisoner",  rarity:"rare"     },
    "Drow Poison":                   { kit:"poisoner",  rarity:"rare"     },
    "Essence of Ether":              { kit:"poisoner",  rarity:"rare"     },
    "Magebane":                      { kit:"poisoner",  rarity:"rare"     },
    "Oil of Taggit":                 { kit:"poisoner",  rarity:"rare"     },
    "Torpor":                        { kit:"poisoner",  rarity:"rare"     },
    // Poisoner – Very Rare
    "Midnight Tears":                { kit:"poisoner",  rarity:"veryRare" },
    "Deathsleep":                    { kit:"poisoner",  rarity:"veryRare" },
    "Water of Death":                { kit:"poisoner",  rarity:"veryRare" },
};

export const WITA_RECIPE_INGREDIENTS = {
    // Alchemist – Common
    "Alchemist's Fire":              ["Fire Peas","Flask of Oil"],
    "Bottled Breath":                ["Air Elemental Wisp"],
    "Blasting Powder":               ["Flame Lily","Charcoal"],
    "Fake Blood":                    ["Bloodroot"],
    "Grenade, Smoke":                ["Flame Lily","Frost Lichen"],
    "Ink, Spell Writing (Common)":   ["Charcoal"],
    "Potion of Climbing":            ["Giant Wolf Spider Hair","Giant Wolf Spider Hair"],
    "Potion of Swimming":            ["Quipper Scale","Quipper Scale","Quipper Scale"],
    "Soothsalts":                    ["Soothsalt Geode"],
    // Alchemist – Uncommon
    "Ink, Spell Writing (Uncommon)": ["Charcoal","Finely Ground Iron"],
    "Invisible Ink":                 ["Pixie's Parasol","Ink"],
    "Lesser Potion of Mana":         ["Pixie's Parasol","Silverthorn"],
    "Midnight Oil":                  ["Flask of Oil","Pixie's Parasol"],
    "Oil of Slipperiness":           ["Flask of Oil","Crawler Mucus","Water Elemental Droplet"],
    "Pixie Dust":                    ["Rainbow Mushroom","Eagle's Feather"],
    "Potion of Animal Friendship":   ["Cat's Tongue","Quipper Scale"],
    "Potion of Fire Breath":         ["Ashblossom","Fire Elemental Ember"],
    "Potion of Growth":              ["Sourgrass","Everfrost Berries","Giant Wolf Spider Hair"],
    "Potion of Resistance":          ["Hagfinger"],
    "Potion of Water Breathing":     ["Gillyweed","Water Elemental Droplet"],
    // Alchemist – Rare
    "Ink, Spell Writing (Rare)":     ["Charcoal","Finely Ground Iron","Willowshade Fruit"],
    "Oil of Dragon's Bane":          ["Dragon's Blood","Wyvern Poison"],
    "Potion of Aqueous Form":        ["Water Elemental Droplet","Gillyweed","Quipper Scale","Quipper Scale","Quipper Scale"],
    "Potion of Gaseous Form":        ["Ectoplasm","Singing Nettle"],
    "Potion of Giant Strength":      ["Frost Lichen","Giant's Nail (Cloud)"],
    "Potion of Mana":                ["Pixie's Parasol","Silverthorn","Dragon's Blood"],
    "Potion of True Dreaming":       ["Nothic Tears","Willowshade Fruit"],
    "Oil of Etherealness":           ["Ectoplasm","Flask of Oil"],
    "Potion of Clairvoyance":        ["Morning Dew","Mandrake Root"],
    "Potion of Diminution":          ["Pixie's Parasol","Moonstalker"],
    "Potion of Heroism":             ["Hagfinger","Cat's Tongue"],
    "Potion of Invulnerability":     ["Lightning Struck Metal"],
    "Potion of Mind Reading":        ["Mindflayer Stinkhorn","Moonstalker"],
    "Thor's Might":                  ["Air Elemental Wisp","Lightning Moss","Singing Nettle"],
    // Alchemist – Very Rare
    "Ink, Spell Writing (Very Rare)":["Charcoal","Finely Ground Iron","Willowshade Oil","Willowshade Oil"],
    "Oil of Sharpness":              ["Ankheg Ichor","Silverthorn"],
    "Potion of Flying":              ["Air Elemental Wisp","Singing Nettle"],
    "Potion of Invisibility":        ["Skulk Claw","Fairy Stool"],
    "Potion of Longevity":           ["Imp Heart","Red Amanita Mushroom"],
    "Potion of Possibility":         ["Skulk Claw","Ectoplasm"],
    "Potion of Speed":               ["Eagle's Claw","Eagle's Claw","Eagle's Claw","Eagle's Claw","Lightning Moss","Sugar"],
    "Potion of Truesight":           ["Fairy Stool","Nothic Tears"],
    "Superior Potion of Mana":       ["Pixie's Parasol","Silverthorn","Dragon's Blood","Remorhaz Ichor"],
    // Herbalism – Common
    "Antitoxin":                     ["Everfrost Berries","Cat's Tongue"],
    "Potion of Healing":             ["Red Amanita Mushroom"],
    "Muroosa Balm":                  ["Flame Lily","Muroosa Bush"],
    "Pepper Peppers":                ["Fire Peas"],
    "Potion of Plantspeak":          ["Cat's Tongue","Muroosa Bush"],
    "Soothing Salve":                ["Sourgrass","Acid Dew"],
    "Quenching Pilther":             ["Muroosa Bush","Gillyweed"],
    "Willowshade Oil":               ["Willowshade Fruit"],
    // Herbalism – Uncommon
    "Blight Ichor":                  ["Blight Spores"],
    "Brew of Babel":                 ["Singing Nettle","Singing Nettle"],
    "Fire Balm":                     ["Flame Lily","Flask of Oil","Theki Root"],
    "Forgetfulness Antidote":        ["The Bearded Green","The Bearded Green","Sourgrass"],
    "Greater Antitoxin":             ["Theki Root","Sourgrass"],
    "Keoghtom's Ointment":           ["Flask of Oil","Theki Root","Red Amanita Mushroom","Red Amanita Mushroom"],
    "Life's Liquor":                 ["Red Amanita Mushroom","Muroosa Bush"],
    "Murgaxor's Elixir of Life":     ["White Ghost Orchid Seed"],
    "Pomander of Warding":           ["Hagfinger"],
    "Potion of Advantage":           ["Willowshade Fruit","Rainbow Mushroom"],
    "Potion of Greater Healing":     ["Red Amanita Mushroom","Red Amanita Mushroom"],
    "Potion of Maximum Power":       ["Theki Root","Olisuba Leaf","Dreamlily"],
    "Potion of Shapeshifting":       ["Rainbow Mushroom","Olisuba Leaf"],
    "Tea of Refreshment":            ["Morning Dew","Cat's Tongue"],
    "Thessaltoxin Antidote":         ["White Ghost Orchid Seed","Theki Root"],
    // Herbalism – Rare
    "Bottled Rest":                  ["Gillyweed","Hagfinger","Morning Dew"],
    "Elixir of Health":              ["Fairy Stool","Gillyweed"],
    "Liquid Luck":                   ["Rainbow Mushroom","Muroosa Bush","Fairy Stool"],
    "Meditative Rest":               ["Fire Peas","Everfrost Berries","Flame Lily"],
    "Polymorph Potion":              ["Rainbow Mushroom","Dreamlily","Willowshade Fruit"],
    "Potion of Restoration":         ["Acid Dew","Acid Dew","Morning Dew","Red Amanita Mushroom","Red Amanita Mushroom"],
    "Potion of Revival":             ["Acid Dew","Dreamlily","White Ghost Orchid Seed"],
    "Potion of Superior Healing":    ["Red Amanita Mushroom","Red Amanita Mushroom","Red Amanita Mushroom"],
    "Tincture of Werewolf's Bane":   ["Wolfsbane","Silverthorn"],
    // Herbalism – Very Rare
    "Reincarnation Dust":            ["Angel's Trumpet","White Ghost Orchid Seed","Lightning Struck Metal","Mandrake Root"],
    "Potion of Continuous Healing":  ["Acid Dew","Red Amanita Mushroom","Red Amanita Mushroom","Red Amanita Mushroom","Olisuba Leaf"],
    "Potion of Enhanced Reactions":  ["Lightning Struck Metal","Idle Claws","Hagfinger"],
    "Potion of Legendary Resistance":["Black Sap","Mindflayer Stinkhorn","Mandrake Root"],
    "Potion of Protection":          ["Hagfinger","Idle Claws","White Ghost Orchid Seed"],
    "Potion of Supreme Healing":     ["Red Amanita Mushroom","Red Amanita Mushroom","Red Amanita Mushroom","Red Amanita Mushroom"],
    "Potion of Vitality":            ["Morning Dew","Morning Dew","Cat's Tongue","Cat's Tongue","Olisuba Leaf"],
    "Vampiric Essence":              ["Bloodroot","Theki Root","Black Cap Mushroom"],
    // Poisoner – Common
    "Basic Poison":                  ["Nightshade"],
    "Biza's Breath":                 ["Angel's Trumpet","Frost Lichen"],
    "Dazzling Bomb":                 ["Nightshade","Gillyweed"],
    "Liquid Paranoia":               ["Moonstalker"],
    "Nausea Pellet":                 ["Sourgrass","Sourgrass"],
    "Perfume of Bewitching":         ["Perfume","Mindflayer Stinkhorn"],
    // Poisoner – Uncommon
    "Angel's Powder":                ["Angel's Trumpet","Dreamlily"],
    "Assassin's Blood":              ["Basic Poison","Nightshade"],
    "Malice":                        ["Morning Dew","Black Sap"],
    "Pale Tincture":                 ["Black Sap","Death Cap"],
    "Philter of Love":               ["Fairy Stool","Serpent's Venom"],
    "Truth Serum":                   ["Fairy Stool","Mindflayer Stinkhorn"],
    // Poisoner – Rare
    "Burnt Othur Fumes":             ["Ashblossom","Moonstalker"],
    "Drow Poison":                   ["Drider Venom","Mandrake Root"],
    "Essence of Ether":              ["Nightshade","Mandrake Root"],
    "Magebane":                      ["Wolfsbane","Drider Venom","Serpent's Venom"],
    "Oil of Taggit":                 ["Flask of Oil","Wolfsbane"],
    "Torpor":                        ["Mandrake Root","Lightning Moss"],
    // Poisoner – Very Rare
    "Midnight Tears":                ["Death Cap","Ankheg Ichor"],
    "Deathsleep":                    ["Tea of Refreshment","Purple Worm Poison"],
    "Water of Death":                ["Black Cap Mushroom","Wyvern Poison","Dreamlily","Hagfinger"],
};
